events:
- channel: C073QS4DUJZ
  end: '2024-05-21'
  name: Apocalypse
  start: '2024-05-16'
  timezone: America/New_York
  users:
  - flights:
    - code: PD2720
      date: '2024-05-17'
    id: U05C64XMMHV
    name: Micha
  - flights:
    - code: WS1221
      date: '2024-05-17'
    id: U04RA9UV3RA
    name: John
  - flights:
    - code: FLE1615
      date: '2024-05-17'
    id: U03MMGVPMFE
    name: Kyle Liao
  - flights:
    - code: PD2946
      date: '2024-05-17'
    id: U056J6JURFF
    name: Sofia Egan
version: 1
