version: 1
events:
- channel: C073QS4DUJZ
  end: '2024-05-21'
  name: Apocalypse
  start: '2024-05-16'
  timezone: America/New_York
- channel: C07CP46USNS
  end: '2024-07-29'
  name: 'The Boreal Express'
  start: '2024-07-19'
  timezone: America/Los_Angeles
