name: check-valid-flights
on: 
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  check-valid-flights:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: "TZ='America/New_York'; export TZ"
      - run: npm install
      - run: node ci.js
        env:
          FLIGHT_API_TOKEN: ${{ secrets.AEROAPI_TOKEN_GH }}
